CREATE procedure [dbo].[ClientMerge] (@ClientIDKeep int, @ClientIDRemove int)
as

set nocount on

--declare @ClientIDKeep int, @ClientIDRemove int
--set @ClientIDKeep = 1
--set @ClientIDRemove = 2


INSERT INTO [Volunteer_DriversSQL].[dbo].[tblMergeRide]
([RideID], [EntryDate] ,[ClientID] ,[RPickUpAddress] ,[RPickupCity] ,[RPickupZip]
,[County] ,[TripPurposeID] ,[TripTypeID] ,[RideDate] ,[RStartTime] ,[REndTime]
,[RTripTime] ,[RDropoffAddress] ,[RDropoffCity] ,[RDropoffZip] ,[RDropoffCounty]
,[LoadedMiles] ,[UnloadedMiles] ,[TotalMiles] ,[MNDOTAllow] ,[ElderlyWaiver]
,[Overnight] ,[AuthCode] ,[RepID] ,[PickupFee] ,[NoShowFee] ,[FMPRIdeID] ,[TripID]
,[FMPTripID] ,[InsuranceID] ,[Rate] ,[RideNotes] ,[SchedulePickupTime] ,[ScheduleApptTime]
,[Canceled] ,[ReimburseRate] ,[ReimburseRateID] ,[Assigned] ,[NoShow] ,[OldAccessDbRideID]
,[RequireIDandAuth] ,[DriverID] ,[SelectCheck] ,[UserCreated] ,[UserUpdated] ,[DateUpdated]
,[DispatchAccessRideID] ,[RequireAuthCode] ,[ClientInsuranceID] ,[MemberID] ,[Lock]
,[FacilityName] ,[SeqNo] ,[PUAddressID] ,[DOAddressID] ,[RPickupZip4] ,[RDropOffZip4]
,[FaciltyZip4] ,[SeniorFitness] ,[rPickupState] ,[rDropOffState] ,[rCancelReason]
,[InEzClaim] ,[MnITSWaver] ,[ChildFamNoWaver] ,[AdultServiceWaver] ,[PublicHealthNoWaver]
,[OnGoing] ,[NewForRides] ,[RoundTrip] ,[OneWay] ,[Waver] ,[MARide]
,[AdultServiceNoWaiver] ,[ACClientMedical] ,[PUAddressTypeID] ,[DOAddressTypeID]
,[EzLinkID] ,[ezclaimphysicianid])

Select [RideID], [EntryDate] ,[ClientID] ,[RPickUpAddress] ,[RPickupCity] ,[RPickupZip]
,[County] ,[TripPurposeID] ,[TripTypeID] ,[RideDate] ,[RStartTime] ,[REndTime]
,[RTripTime] ,[RDropoffAddress] ,[RDropoffCity] ,[RDropoffZip] ,[RDropoffCounty]
,[LoadedMiles] ,[UnloadedMiles] ,[TotalMiles] ,[MNDOTAllow] ,[ElderlyWaiver]
,[Overnight] ,[AuthCode] ,[RepID] ,[PickupFee] ,[NoShowFee] ,[FMPRIdeID] ,[TripID]
,[FMPTripID] ,[InsuranceID] ,[Rate] ,[RideNotes] ,[SchedulePickupTime] ,[ScheduleApptTime]
,[Canceled] ,[ReimburseRate] ,[ReimburseRateID] ,[Assigned] ,[NoShow] ,[OldAccessDbRideID]
,[RequireIDandAuth] ,[DriverID] ,[SelectCheck] ,[UserCreated] ,[UserUpdated] ,[DateUpdated]
,[DispatchAccessRideID] ,[RequireAuthCode] ,[ClientInsuranceID] ,[MemberID] ,[Lock]
,[FacilityName] ,[SeqNo] ,[PUAddressID] ,[DOAddressID] ,[RPickupZip4] ,[RDropOffZip4]
,[FaciltyZip4] ,[SeniorFitness] ,[rPickupState] ,[rDropOffState] ,[rCancelReason]
,[InEzClaim] ,[MnITSWaver] ,[ChildFamNoWaver] ,[AdultServiceWaver] ,[PublicHealthNoWaver]
,[OnGoing] ,[NewForRides] ,[RoundTrip] ,[OneWay] ,[Waver] ,[MARide]
,[AdultServiceNoWaiver] ,[ACClientMedical] ,[PUAddressTypeID] ,[DOAddressTypeID]
,[EzLinkID] ,[ezclaimphysicianid]
from tblride
where Clientid = @ClientIDRemove


update tblRide
set ClientID = @ClientIDKeep
where ClientID = @ClientIDRemove

INSERT INTO [Volunteer_DriversSQL].[dbo].[tblMergeEzClaimPatient]
           ([EzPatient_ID]
           ,[ClientID]
           ,[ClAddressID]
           ,[ClientInsuranceID]
           ,[PatientFirstName]
           ,[PatientLastName]
           ,[PatientMI]
           ,[PatientBirthDate]
           ,[PatientStreetAddress]
           ,[PatientCity]
           ,[PatientState]
           ,[PatientZipCode]
           ,[PatientSex]
           ,[PatientPhoneNo]
           ,[PatientSigOnFile]
           ,[InsuranceType]
           ,[InsuredName]
           ,[InsuredIDNo]
           ,[InsuredGroupNo]
           ,[InsuredStreetAddress]
           ,[InsuredCity]
           ,[InsuredState]
           ,[InsuredZipCode]
           ,[InsuredDOB]
           ,[InsuredSex]
           ,[InsuredPhoneNo]
           ,[InsuredSigOnFile]
           ,[OtherSex]
           ,[PatientRel]
           ,[PatientMarriedStatus]
           ,[PatientEmploymentStatus]
           ,[AnotherPlan]
           ,[RelatedTo]
           ,[OutsideLab]
           ,[PhysicianSigOnFile]
           ,[Diagnosis1]
           ,[AcceptAssignment]
           ,[SSNOrEIN]
           ,[DefaultPlace]
           ,[DefaultDiagnosisCode]
           ,[DefaultCharge]
           ,[DefaultDays]
           ,[DefaultAmountPaid]
           ,[Active]
           ,[Summarize]
           ,[PrintSigDate]
           ,[ServiceDateFormat]
           ,[CurrencyFormat]
           ,[DateFormat]
           ,[DefaultfDays]
           ,[bPhysicianPrintDate]
           ,[bBlankZeroAmounts2930]
           ,[bBlankBox30]
           ,[bPhysicianPhoneOnBottom]
           ,[PrimaryPayerFKey]
           ,[SecondaryPayerFKey]
           ,[bIncludeNotes]
           ,[bBlankAllZeroAmounts]
           ,[ContractID]
           ,[bResponseInd]
           ,[PrintHCFAForm]
           ,[ChangeDate]
           ,[ChangeTime]
           ,[CodeLibraryName]
           ,[ReferringProviderFID]
           ,[FacilityFID]
           ,[DefaultProcedure]
           ,[BillingProviderFID]
           ,[RenderingProviderFID]
           ,[bLockRecord]
           ,[DefaultClaimTemplate]
           ,[OtherPatientRel]
           ,[InsuranceID]
           ,[SelectRecord]
           ,[ExportedDateTime]
           ,[ExportedUserName]
           ,[EZClaimID]
           ,[WarningResults]
           ,[BCBSInsuredMemberIDPattern]
           ,[BCBSInsuredGroupPattern]
           ,[AddressInTable]
           ,[ValidDOB]
           ,[BCBSInsuredGroup]
           ,[UcareIDPattern]
           ,[MedicaIDPattern]
           ,[PUAddressID]
           ,[DOAddressID]
           ,[EzLinkID]
           ,[PatientID]
           ,[UserName])

Select     [EzPatient_ID]
           ,[ClientID]
           ,[ClAddressID]
           ,[ClientInsuranceID]
           ,[PatientFirstName]
           ,[PatientLastName]
           ,[PatientMI]
           ,[PatientBirthDate]
           ,[PatientStreetAddress]
           ,[PatientCity]
           ,[PatientState]
           ,[PatientZipCode]
           ,[PatientSex]
           ,[PatientPhoneNo]
           ,[PatientSigOnFile]
           ,[InsuranceType]
           ,[InsuredName]
           ,[InsuredIDNo]
           ,[InsuredGroupNo]
           ,[InsuredStreetAddress]
           ,[InsuredCity]
           ,[InsuredState]
           ,[InsuredZipCode]
           ,[InsuredDOB]
           ,[InsuredSex]
           ,[InsuredPhoneNo]
           ,[InsuredSigOnFile]
           ,[OtherSex]
           ,[PatientRel]
           ,[PatientMarriedStatus]
           ,[PatientEmploymentStatus]
           ,[AnotherPlan]
           ,[RelatedTo]
           ,[OutsideLab]
           ,[PhysicianSigOnFile]
           ,[Diagnosis1]
           ,[AcceptAssignment]
           ,[SSNOrEIN]
           ,[DefaultPlace]
           ,[DefaultDiagnosisCode]
           ,[DefaultCharge]
           ,[DefaultDays]
           ,[DefaultAmountPaid]
           ,[Active]
           ,[Summarize]
           ,[PrintSigDate]
           ,[ServiceDateFormat]
           ,[CurrencyFormat]
           ,[DateFormat]
           ,[DefaultfDays]
           ,[bPhysicianPrintDate]
           ,[bBlankZeroAmounts2930]
           ,[bBlankBox30]
           ,[bPhysicianPhoneOnBottom]
           ,[PrimaryPayerFKey]
           ,[SecondaryPayerFKey]
           ,[bIncludeNotes]
           ,[bBlankAllZeroAmounts]
           ,[ContractID]
           ,[bResponseInd]
           ,[PrintHCFAForm]
           ,[ChangeDate]
           ,[ChangeTime]
           ,[CodeLibraryName]
           ,[ReferringProviderFID]
           ,[FacilityFID]
           ,[DefaultProcedure]
           ,[BillingProviderFID]
           ,[RenderingProviderFID]
           ,[bLockRecord]
           ,[DefaultClaimTemplate]
           ,[OtherPatientRel]
           ,[InsuranceID]
           ,[SelectRecord]
           ,[ExportedDateTime]
           ,[ExportedUserName]
           ,[EZClaimID]
           ,[WarningResults]
           ,[BCBSInsuredMemberIDPattern]
           ,[BCBSInsuredGroupPattern]
           ,[AddressInTable]
           ,[ValidDOB]
           ,[BCBSInsuredGroup]
           ,[UcareIDPattern]
           ,[MedicaIDPattern]
           ,[PUAddressID]
           ,[DOAddressID]
           ,[EzLinkID]
           ,[PatientID]
           ,[UserName]
 from tblEzClaimPatient
 where Clientid = @ClientIDRemove
 

update tblEzClaimPatient
set ClientID = @ClientIDKeep
where ClientID = @ClientIDRemove

INSERT INTO [Volunteer_DriversSQL].[dbo].[tblMergeEzClaim]
           ([tblEZClaim_ID]
           ,[TripID]
           ,[Insurance]
           ,[ClientID]
           ,[Client]
           ,[RideDate]
           ,[TripType]
           ,[LegCountNotCanceled]
           ,[LegNoShowCount]
           ,[Diagnosis1]
           ,[RenderingPHYFID]
           ,[FacilityAddressID]
           ,[FacilityName]
           ,[AuthCode]
           ,[RepID]
           ,[MemberID]
           ,[ReimburseRate]
           ,[UnloadedReimburseRate]
           ,[SumOfLoadedMiles]
           ,[SumOfUnloadedMiles]
           ,[DeadHeadAuth]
           ,[PaidUnloadedMiles]
           ,[TotalTripMiles]
           ,[PaidMiles]
           ,[UnpaidMiles]
           ,[MealsMisc]
           ,[BillingAmount]
           ,[Insuranceid]
           ,[SelectRecord]
           ,[EzClaimPhysicianID]
           ,[PatientID]
           ,[SeqNo]
           ,[EzLinkID]
           ,[SplitLoadedMiles]
           ,[SplitUnLoadedMiles]
           ,[Warning]
           ,[Fee]
           ,[UserName])
           
select    [tblEZClaim_ID]
           ,[TripID]
           ,[Insurance]
           ,[ClientID]
           ,[Client]
           ,[RideDate]
           ,[TripType]
           ,[LegCountNotCanceled]
           ,[LegNoShowCount]
           ,[Diagnosis1]
           ,[RenderingPHYFID]
           ,[FacilityAddressID]
           ,[FacilityName]
           ,[AuthCode]
           ,[RepID]
           ,[MemberID]
           ,[ReimburseRate]
           ,[UnloadedReimburseRate]
           ,[SumOfLoadedMiles]
           ,[SumOfUnloadedMiles]
           ,[DeadHeadAuth]
           ,[PaidUnloadedMiles]
           ,[TotalTripMiles]
           ,[PaidMiles]
           ,[UnpaidMiles]
           ,[MealsMisc]
           ,[BillingAmount]
           ,[Insuranceid]
           ,[SelectRecord]
           ,[EzClaimPhysicianID]
           ,[PatientID]
           ,[SeqNo]
           ,[EzLinkID]
           ,[SplitLoadedMiles]
           ,[SplitUnLoadedMiles]
           ,[Warning]
           ,[Fee]
           ,[UserName]
 from tblEzClaim
 where Clientid = @ClientIDRemove
 
update tblEzClaim
set ClientID = @ClientIDKeep
where ClientID = @ClientIDRemove
 
 INSERT INTO [Volunteer_DriversSQL].[dbo].[tblMergeEzClaimBilling2]
           ([EzBillingID]
           ,[ClientID]
           ,[TripID]
           ,[FromDate]
           ,[ToDate]
           ,[SeqNo]
           ,[EW]
           ,[OverNight]
           ,[Canceled]
           ,[NoShow]
           ,[SF]
           ,[InEzClaim]
           ,[Pickup]
           ,[DropOff]
           ,[Start Time]
           ,[End Time]
           ,[Place]
           ,[Diagnosis]
           ,[Charges]
           ,[Fdays]
           ,[LineItemGuid]
           ,[CPT]
           ,[Modifier]
           ,[AllowedAmount]
           ,[PayorAmountPaid]
           ,[PurSvcCharge]
           ,[CurrencyCol1]
           ,[CurrencyCol2]
           ,[CurrencyCol3]
           ,[CurrencyCol4]
           ,[CurrencyCol5]
           ,[CurrencyCol6]
           ,[CurrencyCol7]
           ,[CurrencyCol8]
           ,[CoPayAmountDue]
           ,[ApprovedAmt]
           ,[SelectRecord]
           ,[ExportedDateTime]
           ,[ExportedUserName]
           ,[PUAddressID]
           ,[DOAddressID]
           ,[InsuranceID]
           ,[SplitTripID]
           ,[LineItemDescription]
           ,[UserName])
           
 Select    [EzBillingID]
           ,[ClientID]
           ,[TripID]
           ,[FromDate]
           ,[ToDate]
           ,[SeqNo]
           ,[EW]
           ,[OverNight]
           ,[Canceled]
           ,[NoShow]
           ,[SF]
           ,[InEzClaim]
           ,[Pickup]
           ,[DropOff]
           ,[Start Time]
           ,[End Time]
           ,[Place]
           ,[Diagnosis]
           ,[Charges]
           ,[Fdays]
           ,[LineItemGuid]
           ,[CPT]
           ,[Modifier]
           ,[AllowedAmount]
           ,[PayorAmountPaid]
           ,[PurSvcCharge]
           ,[CurrencyCol1]
           ,[CurrencyCol2]
           ,[CurrencyCol3]
           ,[CurrencyCol4]
           ,[CurrencyCol5]
           ,[CurrencyCol6]
           ,[CurrencyCol7]
           ,[CurrencyCol8]
           ,[CoPayAmountDue]
           ,[ApprovedAmt]
           ,[SelectRecord]
           ,[ExportedDateTime]
           ,[ExportedUserName]
           ,[PUAddressID]
           ,[DOAddressID]
           ,[InsuranceID]
           ,[SplitTripID]
           ,[LineItemDescription]
           ,[UserName]
 from tblEzClaimBilling2
 where Clientid = @ClientIDRemove
 
update tblEzClaimBilling2
set ClientID = @ClientIDKeep
where ClientID = @ClientIDRemove
 
 INSERT INTO [Volunteer_DriversSQL].[dbo].[tblMergeEzPatientClientLink2]
           ([EZLinkid]
           ,[timestamp]
           ,[Patientid]
           ,[Clientid]
           ,[Addressid]
           ,[ClientInsuranceid]
           ,[UserName]
           ,[InsuranceID]
           ,[PrimaryPayerFKey]
           ,[Duplicate]
           ,[UpdatedDate])
           
Select     [EZLinkid]
           ,[timestamp]
           ,[Patientid]
           ,[Clientid]
           ,[Addressid]
           ,[ClientInsuranceid]
           ,[UserName]
           ,[InsuranceID]
           ,[PrimaryPayerFKey]
           ,[Duplicate]
           ,[UpdatedDate]
 from EzPatientClientLink2
 where Clientid = @ClientIDRemove
 
update EzPatientClientLink2
set ClientID = @ClientIDKeep
where ClientID = @ClientIDRemove
 
 INSERT INTO [Volunteer_DriversSQL].[dbo].[tblMergeEzClaimPatientHistory]
           ([EzPatientHistory_ID]
           ,[ClientID]
           ,[ClientInsuranceID]
           ,[PatientFirstName]
           ,[PatientLastName]
           ,[PatientMI]
           ,[PatientBirthDate]
           ,[PatientStreetAddress]
           ,[PatientCity]
           ,[PatientState]
           ,[PatientZipCode]
           ,[PatientSex]
           ,[PatientPhoneNo]
           ,[PatientSigOnFile]
           ,[InsuranceType]
           ,[InsuredName]
           ,[InsuredIDNo]
           ,[InsuredGroupNo]
           ,[InsuredStreetAddress]
           ,[InsuredCity]
           ,[InsuredState]
           ,[InsuredZipCode]
           ,[InsuredDOB]
           ,[InsuredSex]
           ,[InsuredPhoneNo]
           ,[InsuredSigOnFile]
           ,[OtherSex]
           ,[PatientRel]
           ,[PatientMarriedStatus]
           ,[PatientEmploymentStatus]
           ,[AnotherPlan]
           ,[RelatedTo]
           ,[OutsideLab]
           ,[PhysicianSigOnFile]
           ,[Diagnosis1]
           ,[AcceptAssignment]
           ,[SSNOrEIN]
           ,[DefaultPlace]
           ,[DefaultDiagnosisCode]
           ,[DefaultCharge]
           ,[DefaultDays]
           ,[DefaultAmountPaid]
           ,[Active]
           ,[Summarize]
           ,[PrintSigDate]
           ,[ServiceDateFormat]
           ,[CurrencyFormat]
           ,[DateFormat]
           ,[DefaultfDays]
           ,[bPhysicianPrintDate]
           ,[bBlankZeroAmounts2930]
           ,[bBlankBox30]
           ,[bPhysicianPhoneOnBottom]
           ,[PrimaryPayerFKey]
           ,[SecondaryPayerFKey]
           ,[bIncludeNotes]
           ,[bBlankAllZeroAmounts]
           ,[ContractID]
           ,[bResponseInd]
           ,[PrintHCFAForm]
           ,[ChangeDate]
           ,[ChangeTime]
           ,[CodeLibraryName]
           ,[ReferringProviderFID]
           ,[FacilityFID]
           ,[DefaultProcedure]
           ,[BillingProviderFID]
           ,[RenderingProviderFID]
           ,[bLockRecord]
           ,[DefaultClaimTemplate]
           ,[OtherPatientRel]
           ,[InsuranceID]
           ,[ExportedDateTime]
           ,[ExportedUserName]
           ,[EZClaimID]
           ,[WarningResults]
           ,[BCBSInsuredMemberIDPattern]
           ,[BCBSInsuredGroupPattern]
           ,[ValidDOB]
           ,[BCBSInsuredGroup]
           ,[UcareIDPattern]
           ,[MedicaIDPattern]
           ,[PUAddressID])
           
Select     [EzPatientHistory_ID]
           ,[ClientID]
           ,[ClientInsuranceID]
           ,[PatientFirstName]
           ,[PatientLastName]
           ,[PatientMI]
           ,[PatientBirthDate]
           ,[PatientStreetAddress]
           ,[PatientCity]
           ,[PatientState]
           ,[PatientZipCode]
           ,[PatientSex]
           ,[PatientPhoneNo]
           ,[PatientSigOnFile]
           ,[InsuranceType]
           ,[InsuredName]
           ,[InsuredIDNo]
           ,[InsuredGroupNo]
           ,[InsuredStreetAddress]
           ,[InsuredCity]
           ,[InsuredState]
           ,[InsuredZipCode]
           ,[InsuredDOB]
           ,[InsuredSex]
           ,[InsuredPhoneNo]
           ,[InsuredSigOnFile]
           ,[OtherSex]
           ,[PatientRel]
           ,[PatientMarriedStatus]
           ,[PatientEmploymentStatus]
           ,[AnotherPlan]
           ,[RelatedTo]
           ,[OutsideLab]
           ,[PhysicianSigOnFile]
           ,[Diagnosis1]
           ,[AcceptAssignment]
           ,[SSNOrEIN]
           ,[DefaultPlace]
           ,[DefaultDiagnosisCode]
           ,[DefaultCharge]
           ,[DefaultDays]
           ,[DefaultAmountPaid]
           ,[Active]
           ,[Summarize]
           ,[PrintSigDate]
           ,[ServiceDateFormat]
           ,[CurrencyFormat]
           ,[DateFormat]
           ,[DefaultfDays]
           ,[bPhysicianPrintDate]
           ,[bBlankZeroAmounts2930]
           ,[bBlankBox30]
           ,[bPhysicianPhoneOnBottom]
           ,[PrimaryPayerFKey]
           ,[SecondaryPayerFKey]
           ,[bIncludeNotes]
           ,[bBlankAllZeroAmounts]
           ,[ContractID]
           ,[bResponseInd]
           ,[PrintHCFAForm]
           ,[ChangeDate]
           ,[ChangeTime]
           ,[CodeLibraryName]
           ,[ReferringProviderFID]
           ,[FacilityFID]
           ,[DefaultProcedure]
           ,[BillingProviderFID]
           ,[RenderingProviderFID]
           ,[bLockRecord]
           ,[DefaultClaimTemplate]
           ,[OtherPatientRel]
           ,[InsuranceID]
           ,[ExportedDateTime]
           ,[ExportedUserName]
           ,[EZClaimID]
           ,[WarningResults]
           ,[BCBSInsuredMemberIDPattern]
           ,[BCBSInsuredGroupPattern]
           ,[ValidDOB]
           ,[BCBSInsuredGroup]
           ,[UcareIDPattern]
           ,[MedicaIDPattern]
           ,[PUAddressID]
 from tblEzClaimPatientHistory
 where Clientid = @ClientIDRemove
 
update tblEzClaimPatientHistory
set ClientID = @ClientIDKeep
where ClientID = @ClientIDRemove
 
 INSERT INTO [Volunteer_DriversSQL].[dbo].[tblMergeArchiveRide]
           ([RideID]
           ,[EntryDate]
           ,[ClientID]
           ,[ClFN]
           ,[ClLN]
           ,[ClPhone]
           ,[tblClient_ClientType]
           ,[tblClient_MemberID]
           ,[ClNotes]
           ,[ltblClientType_ClientType]
           ,[tblClientInsurance_MemberID]
           ,[ClientInsuranceNotes]
           ,[MaxAllowedByInsurancePerTrip]
           ,[RPickupZip]
           ,[tblRide_County]
           ,[ltblCounty_County]
           ,[ltblCounty_MIPCountyCode]
           ,[TripPurposeID]
           ,[TripPurpose]
           ,[TripTypeID]
           ,[TripType]
           ,[RDropoffCounty]
           ,[ltblCounty_2_County]
           ,[ltblCounty_2_MIPCountyCode]
           ,[Insurance]
           ,[RequireIDandAuth]
           ,[ArchiveUser]
           ,[ArchiveDateTime])
           
select     [RideID]
           ,[EntryDate]
           ,[ClientID]
           ,[ClFN]
           ,[ClLN]
           ,[ClPhone]
           ,[tblClient_ClientType]
           ,[tblClient_MemberID]
           ,[ClNotes]
           ,[ltblClientType_ClientType]
           ,[tblClientInsurance_MemberID]
           ,[ClientInsuranceNotes]
           ,[MaxAllowedByInsurancePerTrip]
           ,[RPickupZip]
           ,[tblRide_County]
           ,[ltblCounty_County]
           ,[ltblCounty_MIPCountyCode]
           ,[TripPurposeID]
           ,[TripPurpose]
           ,[TripTypeID]
           ,[TripType]
           ,[RDropoffCounty]
           ,[ltblCounty_2_County]
           ,[ltblCounty_2_MIPCountyCode]
           ,[Insurance]
           ,[RequireIDandAuth]
           ,[ArchiveUser]
           ,[ArchiveDateTime]
from tblArchiveRide
where Clientid = @ClientIDRemove

update tblArchiveRide
set ClientID = @ClientIDKeep
where ClientID = @ClientIDRemove

INSERT INTO [Volunteer_DriversSQL].[dbo].[tblMergeEzClaimHistory]
           ([tblEZClaimHistory_ID]
           ,[TripID]
           ,[Insurance]
           ,[ClientID]
           ,[Client]
           ,[RideDate]
           ,[TripType]
           ,[LegCountNotCanceled]
           ,[LegNoShowCount]
           ,[Diagnosis1]
           ,[RenderingPHYFID]
           ,[FacilityAddressID]
           ,[FacilityName]
           ,[AuthCode]
           ,[RepID]
           ,[MemberID]
           ,[ReimburseRate]
           ,[UnloadedReimburseRate]
           ,[SumOfLoadedMiles]
           ,[SumOfUnloadedMiles]
           ,[DeadHeadAuth]
           ,[PaidUnloadedMiles]
           ,[TotalTripMiles]
           ,[PaidMiles]
           ,[UnpaidMiles]
           ,[MealsMisc]
           ,[BillingAmount]
           ,[Insuranceid]
           ,[SelectRecord]
           ,[EzClaimPhysicianID]
           ,[PatientID]
           ,[SeqNo]
           ,[ExportedDatetime]
           ,[ExportedUserName])

select     [tblEZClaimHistory_ID]
           ,[TripID]
           ,[Insurance]
           ,[ClientID]
           ,[Client]
           ,[RideDate]
           ,[TripType]
           ,[LegCountNotCanceled]
           ,[LegNoShowCount]
           ,[Diagnosis1]
           ,[RenderingPHYFID]
           ,[FacilityAddressID]
           ,[FacilityName]
           ,[AuthCode]
           ,[RepID]
           ,[MemberID]
           ,[ReimburseRate]
           ,[UnloadedReimburseRate]
           ,[SumOfLoadedMiles]
           ,[SumOfUnloadedMiles]
           ,[DeadHeadAuth]
           ,[PaidUnloadedMiles]
           ,[TotalTripMiles]
           ,[PaidMiles]
           ,[UnpaidMiles]
           ,[MealsMisc]
           ,[BillingAmount]
           ,[Insuranceid]
           ,[SelectRecord]
           ,[EzClaimPhysicianID]
           ,[PatientID]
           ,[SeqNo]
           ,[ExportedDatetime]
           ,[ExportedUserName]
from tblEzClaimHistory
where Clientid = @ClientIDRemove

update tblEzClaimHistory
set ClientID = @ClientIDKeep
where ClientID = @ClientIDRemove

INSERT INTO [Volunteer_DriversSQL].[dbo].[tblMergeEzClaimBillingHistory]
           ([EzBillingHistoryID]
           ,[ClientID]
           ,[TripID]
           ,[FromDate]
           ,[ToDate]
           ,[SeqNo]
           ,[EW]
           ,[OverNight]
           ,[Canceled]
           ,[NoShow]
           ,[SF]
           ,[InEzClaim]
           ,[Pickup]
           ,[DropOff]
           ,[Start Time]
           ,[End Time]
           ,[Place]
           ,[Diagnosis]
           ,[Charges]
           ,[Fdays]
           ,[LineItemGuid]
           ,[CPT]
           ,[Modifier]
           ,[AllowedAmount]
           ,[PayorAmountPaid]
           ,[PurSvcCharge]
           ,[CurrencyCol1]
           ,[CurrencyCol2]
           ,[CurrencyCol3]
           ,[CurrencyCol4]
           ,[CurrencyCol5]
           ,[CurrencyCol6]
           ,[CurrencyCol7]
           ,[CurrencyCol8]
           ,[CoPayAmountDue]
           ,[ApprovedAmt]
           ,[PUAddressID]
           ,[DOAddressID]
           ,[ExportedDatetime]
           ,[ExportedUserName]
           ,[InsuranceID])
           
 select    [EzBillingHistoryID]
           ,[ClientID]
           ,[TripID]
           ,[FromDate]
           ,[ToDate]
           ,[SeqNo]
           ,[EW]
           ,[OverNight]
           ,[Canceled]
           ,[NoShow]
           ,[SF]
           ,[InEzClaim]
           ,[Pickup]
           ,[DropOff]
           ,[Start Time]
           ,[End Time]
           ,[Place]
           ,[Diagnosis]
           ,[Charges]
           ,[Fdays]
           ,[LineItemGuid]
           ,[CPT]
           ,[Modifier]
           ,[AllowedAmount]
           ,[PayorAmountPaid]
           ,[PurSvcCharge]
           ,[CurrencyCol1]
           ,[CurrencyCol2]
           ,[CurrencyCol3]
           ,[CurrencyCol4]
           ,[CurrencyCol5]
           ,[CurrencyCol6]
           ,[CurrencyCol7]
           ,[CurrencyCol8]
           ,[CoPayAmountDue]
           ,[ApprovedAmt]
           ,[PUAddressID]
           ,[DOAddressID]
           ,[ExportedDatetime]
           ,[ExportedUserName]
           ,[InsuranceID]
 from tblEzClaimBillingHistory
 where Clientid = @ClientIDRemove
 
update tblEzClaimBillingHistory
set ClientID = @ClientIDKeep
where ClientID = @ClientIDRemove
 
 
 INSERT INTO [Volunteer_DriversSQL].[dbo].[tblMergeEzPatientClientLinkOld]
           ([EZLinkid]
           ,[timestamp]
           ,[Patientid]
           ,[Clientid]
           ,[Addressid]
           ,[ClientInsuranceid]
           ,[UserName]
           ,[InsuranceID]
           ,[PrimaryPayerFKey]
           ,[Duplicate]
           ,[UpdatedDate])

Select     [EZLinkid]
           ,[timestamp]
           ,[Patientid]
           ,[Clientid]
           ,[Addressid]
           ,[ClientInsuranceid]
           ,[UserName]
           ,[InsuranceID]
           ,[PrimaryPayerFKey]
           ,[Duplicate]
           ,[UpdatedDate]
from EzPatientClientLinkOld
where Clientid = @ClientIDRemove

update EzPatientClientLinkOld
set ClientID = @ClientIDKeep
where ClientID = @ClientIDRemove

INSERT INTO [Volunteer_DriversSQL].[dbo].[tblMergeClientAddress]
           ([ClientAddressID]
           ,[ClientID]
           ,[StartDate]
           ,[EndDate]
           ,[EntryDate]
           ,[ClAddress]
           ,[ClCity]
           ,[ClState]
           ,[ClZip]
           ,[County]
           ,[AddressType]
           ,[Active]
           ,[UserCreated]
           ,[UserUpdated]
           ,[DateUpdated]
           ,[ClAddressID]
           ,[EzClaimPatientID])
           
Select     [ClientAddressID]
           ,[ClientID]
           ,[StartDate]
           ,[EndDate]
           ,[EntryDate]
           ,[ClAddress]
           ,[ClCity]
           ,[ClState]
           ,[ClZip]
           ,[County]
           ,[AddressType]
           ,[Active]
           ,[UserCreated]
           ,[UserUpdated]
           ,[DateUpdated]
           ,[ClAddressID]
           ,[EzClaimPatientID]
From tblClientAddress
where Clientid = @ClientIDRemove

update tblClientAddress
set ClientID = @ClientIDKeep
where ClientID = @ClientIDRemove

INSERT INTO [Volunteer_DriversSQL].[dbo].[tblMergeClientInsurance]
           ([ClientInsuranceID]
           ,[ClientID]
           ,[InsuranceID]
           ,[StartDate]
           ,[EndDate]
           ,[EntryDate]
           ,[Active]
           ,[MemberID]
           ,[ClientInsuranceNotes]
           ,[MaxAllowedByInsurancePerTrip]
           ,[UserCreated]
           ,[UserUpdated]
           ,[DateUpdated]
           ,[GroupID]
           ,[RevokeDate]
           ,[BenefitsCheck])
           
Select     [ClientInsuranceID]
           ,[ClientID]
           ,[InsuranceID]
           ,[StartDate]
           ,[EndDate]
           ,[EntryDate]
           ,[Active]
           ,[MemberID]
           ,[ClientInsuranceNotes]
           ,[MaxAllowedByInsurancePerTrip]
           ,[UserCreated]
           ,[UserUpdated]
           ,[DateUpdated]
           ,[GroupID]
           ,[RevokeDate]
           ,[BenefitsCheck]
 From tblClientInsurance
 where Clientid = @ClientIDRemove
 
update tblClientInsurance
set ClientID = @ClientIDKeep
where ClientID = @ClientIDRemove
 
 INSERT INTO [Volunteer_DriversSQL].[dbo].[tblMergeClientDriverDistance]
           ([ClientDriverID]
           ,[ClientID]
           ,[ClientAddressID]
           ,[DriverID]
           ,[DriverAddressID]
           ,[Active]
           ,[Distance]
           ,[LastRideDate])
           
Select     [ClientDriverID]
           ,[ClientID]
           ,[ClientAddressID]
           ,[DriverID]
           ,[DriverAddressID]
           ,[Active]
           ,[Distance]
           ,[LastRideDate]
From tblClientDriverDistance
where Clientid = @ClientIDRemove

update tblClientDriverDistance
set ClientID = @ClientIDKeep
where ClientID = @ClientIDRemove

INSERT INTO [Volunteer_DriversSQL].[dbo].[tblMergeEzclaimhistorytemp]
           ([tblEZClaimHistory_ID]
           ,[TripID]
           ,[Insurance]
           ,[ClientID]
           ,[Client]
           ,[RideDate]
           ,[TripType]
           ,[LegCountNotCanceled]
           ,[LegNoShowCount]
           ,[Diagnosis1]
           ,[RenderingPHYFID]
           ,[FacilityAddressID]
           ,[FacilityName]
           ,[AuthCode]
           ,[RepID]
           ,[MemberID]
           ,[ReimburseRate]
           ,[UnloadedReimburseRate]
           ,[SumOfLoadedMiles]
           ,[SumOfUnloadedMiles]
           ,[DeadHeadAuth]
           ,[PaidUnloadedMiles]
           ,[TotalTripMiles]
           ,[PaidMiles]
           ,[UnpaidMiles]
           ,[MealsMisc]
           ,[BillingAmount]
           ,[Insuranceid]
           ,[SelectRecord]
           ,[EzClaimPhysicianID]
           ,[PatientID]
           ,[SeqNo]
           ,[ExportedDatetime]
           ,[ExportedUserName])

Select     [tblEZClaimHistory_ID]
           ,[TripID]
           ,[Insurance]
           ,[ClientID]
           ,[Client]
           ,[RideDate]
           ,[TripType]
           ,[LegCountNotCanceled]
           ,[LegNoShowCount]
           ,[Diagnosis1]
           ,[RenderingPHYFID]
           ,[FacilityAddressID]
           ,[FacilityName]
           ,[AuthCode]
           ,[RepID]
           ,[MemberID]
           ,[ReimburseRate]
           ,[UnloadedReimburseRate]
           ,[SumOfLoadedMiles]
           ,[SumOfUnloadedMiles]
           ,[DeadHeadAuth]
           ,[PaidUnloadedMiles]
           ,[TotalTripMiles]
           ,[PaidMiles]
           ,[UnpaidMiles]
           ,[MealsMisc]
           ,[BillingAmount]
           ,[Insuranceid]
           ,[SelectRecord]
           ,[EzClaimPhysicianID]
           ,[PatientID]
           ,[SeqNo]
           ,[ExportedDatetime]
           ,[ExportedUserName]
From tblEzclaimhistorytemp
where Clientid = @ClientIDRemove

update tblEzclaimhistorytemp
set ClientID = @ClientIDKeep
where ClientID = @ClientIDRemove

INSERT INTO [Volunteer_DriversSQL].[dbo].[tblMergeEzpatientclientlink2temp]
           ([EZLinkid]
           ,[timestamp]
           ,[Patientid]
           ,[Clientid]
           ,[Addressid]
           ,[ClientInsuranceid]
           ,[UserName]
           ,[InsuranceID]
           ,[PrimaryPayerFKey]
           ,[Duplicate]
           ,[UpdatedDate])
           
Select     [EZLinkid]
           ,[timestamp]
           ,[Patientid]
           ,[Clientid]
           ,[Addressid]
           ,[ClientInsuranceid]
           ,[UserName]
           ,[InsuranceID]
           ,[PrimaryPayerFKey]
           ,[Duplicate]
           ,[UpdatedDate]
From Ezpatientclientlink2temp
where Clientid = @ClientIDRemove

update Ezpatientclientlink2temp
set ClientID = @ClientIDKeep
where ClientID = @ClientIDRemove

INSERT INTO [Volunteer_DriversSQL].[dbo].[tblMergeEzClaimExportMods]
           ([EzExportID]
           ,[Client]
           ,[RideDate]
           ,[TripID]
           ,[Insurance]
           ,[Mod1]
           ,[Mod2]
           ,[Mod3]
           ,[Mod4]
           ,[Mod5]
           ,[Mod6]
           ,[Mod7]
           ,[Mod8]
           ,[UserName]
           ,[ClaimID]
           ,[PatientID]
           ,[ClientID])
           
Select     [EzExportID]
           ,[Client]
           ,[RideDate]
           ,[TripID]
           ,[Insurance]
           ,[Mod1]
           ,[Mod2]
           ,[Mod3]
           ,[Mod4]
           ,[Mod5]
           ,[Mod6]
           ,[Mod7]
           ,[Mod8]
           ,[UserName]
           ,[ClaimID]
           ,[PatientID]
           ,[ClientID]
From tblEzClaimExportMods
where Clientid = @ClientIDRemove

update tblEzClaimExportMods
set ClientID = @ClientIDKeep
where ClientID = @ClientIDRemove

INSERT INTO [Volunteer_DriversSQL].[dbo].[tblMergeClient]
           ([ClientID]
           ,[Active]
           ,[EntryDate]
           ,[ClFN]
           ,[ClLN]
           ,[ClPhone]
           ,[ClientType]
           ,[Insurance]
           ,[MemberID]
           ,[FMPClientID]
           ,[ClAddress]
           ,[ClCity]
           ,[ClState]
           ,[ClZip]
           ,[County]
           ,[ClNotes]
           ,[FMPTripClientName]
           ,[LNCommaFirst]
           ,[MigrateInsuranceText]
           ,[UserCreated]
           ,[UserUpdated]
           ,[DateUpdated]
           ,[DOB]
           ,[ClDOB]
           ,[ClMI]
           ,[Gender]
           ,[Suffix])

select     [ClientID]
           ,[Active]
           ,[EntryDate]
           ,[ClFN]
           ,[ClLN]
           ,[ClPhone]
           ,[ClientType]
           ,[Insurance]
           ,[MemberID]
           ,[FMPClientID]
           ,[ClAddress]
           ,[ClCity]
           ,[ClState]
           ,[ClZip]
           ,[County]
           ,[ClNotes]
           ,[FMPTripClientName]
           ,[LNCommaFirst]
           ,[MigrateInsuranceText]
           ,[UserCreated]
           ,[UserUpdated]
           ,[DateUpdated]
           ,[DOB]
           ,[ClDOB]
           ,[ClMI]
           ,[Gender]
           ,[Suffix]
from tblClient
where Clientid = @ClientIDRemove

--merge client notes
update tblClient
set tblClient.ClNotes = cast(cast(isnull(tblClient.ClNotes,'') as nvarchar(max)) + ' ' +  cast(isnull(c.clNotes,'') as nvarchar(max)) as ntext)
from tblClient
inner join tblClient c
on c.ClientID = @ClientIDRemove
and tblClient.ClientID = @ClientIDKeep


delete from tblClient
where ClientID = @ClientIDRemove