CREATE TABLE [dbo].[tblEzClaimPatient] (
    [EzPatient_ID]               INT           IDENTITY (1, 1) NOT NULL,
    [ClientID]                   INT           NOT NULL,
    [ClAddressID]                INT           NULL,
    [ClientInsuranceID]          INT           NOT NULL,
    [PatientFirstName]           VARCHAR (50)  NULL,
    [PatientLastName]            VARCHAR (50)  NULL,
    [PatientMI]                  VARCHAR (5)   NULL,
    [PatientBirthDate]           DATETIME      NULL,
    [PatientStreetAddress]       VARCHAR (50)  NULL,
    [PatientCity]                VARCHAR (50)  NULL,
    [PatientState]               VARCHAR (10)  NULL,
    [PatientZipCode]             VARCHAR (20)  NULL,
    [PatientSex]                 INT           NULL,
    [PatientPhoneNo]             VARCHAR (25)  NULL,
    [PatientSigOnFile]           INT           NOT NULL,
    [InsuranceType]              INT           NOT NULL,
    [InsuredName]                VARCHAR (50)  NULL,
    [InsuredIDNo]                VARCHAR (50)  NULL,
    [InsuredGroupNo]             VARCHAR (50)  NULL,
    [InsuredStreetAddress]       VARCHAR (50)  NULL,
    [InsuredCity]                VARCHAR (50)  NULL,
    [InsuredState]               VARCHAR (20)  NULL,
    [InsuredZipCode]             VARCHAR (20)  NULL,
    [InsuredDOB]                 DATETIME      NULL,
    [InsuredSex]                 INT           NOT NULL,
    [InsuredPhoneNo]             VARCHAR (25)  NULL,
    [InsuredSigOnFile]           INT           NOT NULL,
    [OtherSex]                   INT           NOT NULL,
    [PatientRel]                 INT           NOT NULL,
    [PatientMarriedStatus]       INT           NOT NULL,
    [PatientEmploymentStatus]    INT           NOT NULL,
    [AnotherPlan]                INT           NOT NULL,
    [RelatedTo]                  INT           NOT NULL,
    [OutsideLab]                 INT           NOT NULL,
    [PhysicianSigOnFile]         INT           NOT NULL,
    [Diagnosis1]                 VARCHAR (20)  NULL,
    [AcceptAssignment]           INT           NOT NULL,
    [SSNOrEIN]                   INT           NOT NULL,
    [DefaultPlace]               VARCHAR (5)   NOT NULL,
    [DefaultDiagnosisCode]       VARCHAR (15)  NOT NULL,
    [DefaultCharge]              MONEY         NOT NULL,
    [DefaultDays]                INT           NOT NULL,
    [DefaultAmountPaid]          MONEY         NOT NULL,
    [Active]                     INT           NOT NULL,
    [Summarize]                  INT           NOT NULL,
    [PrintSigDate]               INT           NOT NULL,
    [ServiceDateFormat]          VARCHAR (20)  NOT NULL,
    [CurrencyFormat]             VARCHAR (20)  NOT NULL,
    [DateFormat]                 VARCHAR (20)  NOT NULL,
    [DefaultfDays]               INT           NOT NULL,
    [bPhysicianPrintDate]        INT           NOT NULL,
    [bBlankZeroAmounts2930]      INT           NOT NULL,
    [bBlankBox30]                INT           NULL,
    [bPhysicianPhoneOnBottom]    INT           NOT NULL,
    [PrimaryPayerFKey]           BIGINT        NULL,
    [SecondaryPayerFKey]         BIGINT        NOT NULL,
    [bIncludeNotes]              INT           NOT NULL,
    [bBlankAllZeroAmounts]       INT           NOT NULL,
    [ContractID]                 BIGINT        NULL,
    [bResponseInd]               INT           NOT NULL,
    [PrintHCFAForm]              INT           NOT NULL,
    [ChangeDate]                 VARCHAR (8)   NULL,
    [ChangeTime]                 VARCHAR (14)  NULL,
    [CodeLibraryName]            VARCHAR (50)  NOT NULL,
    [ReferringProviderFID]       BIGINT        NOT NULL,
    [FacilityFID]                BIGINT        NOT NULL,
    [DefaultProcedure]           VARCHAR (48)  NOT NULL,
    [BillingProviderFID]         BIGINT        NOT NULL,
    [RenderingProviderFID]       BIGINT        NOT NULL,
    [bLockRecord]                INT           NOT NULL,
    [DefaultClaimTemplate]       VARCHAR (255) CONSTRAINT [DF_tblEzClaimPatient_DefaultClaimTemplate] DEFAULT ('<Use Initial Charge Values>') NOT NULL,
    [OtherPatientRel]            INT           NOT NULL,
    [InsuranceID]                INT           NULL,
    [SelectRecord]               BIT           CONSTRAINT [DF__tblEzClai__Selec__15A53433] DEFAULT ((1)) NOT NULL,
    [ExportedDateTime]           DATETIME      NULL,
    [ExportedUserName]           VARCHAR (50)  NULL,
    [EZClaimID]                  INT           NULL,
    [WarningResults]             VARCHAR (255) NULL,
    [BCBSInsuredMemberIDPattern] VARCHAR (255) NULL,
    [BCBSInsuredGroupPattern]    VARCHAR (255) NULL,
    [AddressInTable]             VARCHAR (255) NULL,
    [ValidDOB]                   VARCHAR (255) NULL,
    [BCBSInsuredGroup]           VARCHAR (255) NULL,
    [UcareIDPattern]             VARCHAR (255) NULL,
    [MedicaIDPattern]            VARCHAR (255) NULL,
    [PUAddressID]                INT           NULL,
    [DOAddressID]                INT           NULL,
    [EzLinkID]                   INT           NULL,
    [PatientID]                  INT           NULL,
    [UserName]                   VARCHAR (50)  NULL,
    CONSTRAINT [PK_tblEzClaimPatient] PRIMARY KEY CLUSTERED ([EzPatient_ID] ASC)
);

