CREATE TABLE [dbo].[tblEzClaimPhysicianHistory] (
    [EzPhysicianHistory_id]     INT           IDENTITY (1, 1) NOT NULL,
    [PhyRecID]                  INT           NULL,
    [PhyName]                   VARCHAR (50)  NULL,
    [PhyEntityType]             CHAR (1)      NOT NULL,
    [PhyLastName]               VARCHAR (35)  NULL,
    [PhyAddress1]               VARCHAR (55)  NOT NULL,
    [PhyCity]                   VARCHAR (30)  NOT NULL,
    [PhyState]                  CHAR (2)      NOT NULL,
    [PhyZip]                    VARCHAR (15)  NOT NULL,
    [PhyType]                   VARCHAR (50)  NOT NULL,
    [PhysicianDateTimeCreated]  DATETIME      NOT NULL,
    [PhysicianDateTimeModified] DATETIME      NOT NULL,
    [PhyInactive]               INT           NOT NULL,
    [AddressID]                 INT           NULL,
    [EzclaimID]                 INT           NULL,
    [Warning]                   VARCHAR (255) NULL,
    [ModCheck]                  VARCHAR (255) NULL,
    [Zip4Check]                 VARCHAR (255) NULL,
    [InsuranceID]               INT           NULL,
    [EnteredDate]               DATETIME      NULL,
    [Canceled]                  BIT           NULL,
    [Modifier]                  VARCHAR (10)  NULL,
    [AddTypeDesc]               VARCHAR (50)  NULL,
    [ExportedDateTime]          DATETIME      NULL,
    [ExportedUserName]          VARCHAR (50)  NULL,
    CONSTRAINT [PK_tblEzClaimPhysicianHistory] PRIMARY KEY CLUSTERED ([EzPhysicianHistory_id] ASC)
);

