CREATE TABLE [dbo].[tblMergeClient] (
    [MergeClientID]        INT            IDENTITY (1, 1) NOT NULL,
    [ClientID]             INT            NULL,
    [Active]               BIT            NULL,
    [EntryDate]            DATETIME       NULL,
    [ClFN]                 NVARCHAR (255) NULL,
    [ClLN]                 NVARCHAR (255) NULL,
    [ClPhone]              NVARCHAR (255) NULL,
    [ClientType]           INT            NULL,
    [Insurance]            INT            NULL,
    [MemberID]             NVARCHAR (255) NULL,
    [FMPClientID]          INT            NULL,
    [ClAddress]            NVARCHAR (255) NULL,
    [ClCity]               NVARCHAR (255) NULL,
    [ClState]              NVARCHAR (255) NULL,
    [ClZip]                NVARCHAR (255) NULL,
    [County]               INT            NULL,
    [ClNotes]              NTEXT          NULL,
    [FMPTripClientName]    NVARCHAR (255) NULL,
    [LNCommaFirst]         NVARCHAR (255) NULL,
    [upsize_ts]            ROWVERSION     NULL,
    [MigrateInsuranceText] NVARCHAR (50)  NULL,
    [UserCreated]          CHAR (30)      NULL,
    [UserUpdated]          CHAR (30)      NULL,
    [DateUpdated]          DATETIME       NULL,
    [DOB]                  DATE           NULL,
    [ClDOB]                DATETIME       NULL,
    [ClMI]                 CHAR (1)       NULL,
    [Gender]               INT            NULL,
    [Suffix]               VARCHAR (10)   NULL
);

