CREATE TABLE [dbo].[ftptest] (
    [vendor]                       INT            NULL,
    [seqrideid]                    INT            NULL,
    [seqridelegid]                 INT            NULL,
    [status]                       INT            NULL,
    [ridedate]                     DATETIME       NULL,
    [primaryRiderExternalMemberID] NVARCHAR (255) NULL,
    [primaryRiderLastName]         NVARCHAR (255) NULL,
    [primaryRiderFirstName]        NVARCHAR (255) NULL,
    [primaryridermiddleinitial]    CHAR (1)       NULL,
    [cabridetype]                  INT            NULL,
    [pickupdate]                   DATETIME       NULL,
    [appointmentdate]              DATETIME       NULL,
    [fromfacilityname]             VARCHAR (100)  NULL,
    [fromstreet]                   VARCHAR (70)   NULL,
    [fromstreet2]                  VARCHAR (70)   NULL,
    [fromcity]                     VARCHAR (25)   NULL,
    [fromstate]                    VARCHAR (2)    NULL,
    [fromzip]                      VARCHAR (10)   NULL,
    [fromcounty]                   NVARCHAR (255) NULL,
    [fromphone]                    VARCHAR (255)  NULL,
    [tofacilityname]               VARCHAR (100)  NULL,
    [tostreet]                     VARCHAR (70)   NULL,
    [tostreet2]                    VARCHAR (70)   NULL,
    [tocity]                       VARCHAR (25)   NULL,
    [tostate]                      VARCHAR (2)    NULL,
    [tozip]                        VARCHAR (10)   NULL,
    [tocounty]                     NVARCHAR (255) NULL,
    [tophone]                      VARCHAR (255)  NULL,
    [numberofriders]               INT            NULL,
    [estimatedmileage]             DECIMAL (7, 3) NULL,
    [instructions]                 VARCHAR (MAX)  NULL,
    [modified]                     INT            NULL,
    [primaryriderstreet1]          VARCHAR (70)   NULL,
    [primaryriderstreet2]          VARCHAR (70)   NULL,
    [primaryridercity]             VARCHAR (25)   NULL,
    [primaryriderstate]            VARCHAR (2)    NULL,
    [primaryriderzip]              VARCHAR (10)   NULL,
    [Primaryridercounty]           NVARCHAR (255) NULL,
    [primaryriderphone]            VARCHAR (255)  NULL,
    [primaryridergender]           VARCHAR (10)   NULL,
    [primaryriderdateofbirth]      DATETIME       NULL,
    [mode]                         INT            NULL,
    [fromzip4]                     CHAR (4)       NULL,
    [tozip4]                       CHAR (4)       NULL
);



