CREATE TABLE [dbo].[tblCityDistances] (
    [F1]                     NVARCHAR (255) NULL,
    [Ada]                    FLOAT (53)     NULL,
    [Adrian]                 FLOAT (53)     NULL,
    [Afton]                  FLOAT (53)     NULL,
    [Aitkin]                 FLOAT (53)     NULL,
    [Albany]                 FLOAT (53)     NULL,
    [Albert Lea]             FLOAT (53)     NULL,
    [Albertville]            FLOAT (53)     NULL,
    [Alexandria]             FLOAT (53)     NULL,
    [Andover]                FLOAT (53)     NULL,
    [Annandale]              FLOAT (53)     NULL,
    [Anoka]                  FLOAT (53)     NULL,
    [Apple Valley]           FLOAT (53)     NULL,
    [Appleton]               FLOAT (53)     NULL,
    [Arden Hills]            FLOAT (53)     NULL,
    [Arlington]              FLOAT (53)     NULL,
    [Arnold]                 FLOAT (53)     NULL,
    [Atwater]                FLOAT (53)     NULL,
    [Aurora]                 FLOAT (53)     NULL,
    [Austin]                 FLOAT (53)     NULL,
    [Avon]                   FLOAT (53)     NULL,
    [Babbitt]                FLOAT (53)     NULL,
    [Bagley]                 FLOAT (53)     NULL,
    [Barnesville]            FLOAT (53)     NULL,
    [Baudette]               FLOAT (53)     NULL,
    [Baxter]                 FLOAT (53)     NULL,
    [Bayport]                FLOAT (53)     NULL,
    [Becker]                 FLOAT (53)     NULL,
    [Belle Plaine]           FLOAT (53)     NULL,
    [Bemidji]                FLOAT (53)     NULL,
    [Benson]                 FLOAT (53)     NULL,
    [Big Lake]               FLOAT (53)     NULL,
    [Birchwood]              FLOAT (53)     NULL,
    [Bird Island]            FLOAT (53)     NULL,
    [Blaine]                 FLOAT (53)     NULL,
    [Blooming Prairie]       FLOAT (53)     NULL,
    [Bloomington]            FLOAT (53)     NULL,
    [Blue Earth]             FLOAT (53)     NULL,
    [Braham]                 FLOAT (53)     NULL,
    [Brainerd]               FLOAT (53)     NULL,
    [Breckenridge]           FLOAT (53)     NULL,
    [Breezy Point]           FLOAT (53)     NULL,
    [Brooklyn Center]        FLOAT (53)     NULL,
    [Brooklyn Park]          FLOAT (53)     NULL,
    [Buffalo]                FLOAT (53)     NULL,
    [Burnsville]             FLOAT (53)     NULL,
    [Byron]                  FLOAT (53)     NULL,
    [Caledonia]              FLOAT (53)     NULL,
    [Cambridge]              FLOAT (53)     NULL,
    [Canby]                  FLOAT (53)     NULL,
    [Cannon Falls]           FLOAT (53)     NULL,
    [Carver]                 FLOAT (53)     NULL,
    [Centerville]            FLOAT (53)     NULL,
    [Champlin]               FLOAT (53)     NULL,
    [Chanhassen]             FLOAT (53)     NULL,
    [Chaska]                 FLOAT (53)     NULL,
    [Chatfield]              FLOAT (53)     NULL,
    [Chisago City]           FLOAT (53)     NULL,
    [Chisholm]               FLOAT (53)     NULL,
    [Circle Pines]           FLOAT (53)     NULL,
    [Clara City]             FLOAT (53)     NULL,
    [Clearwater]             FLOAT (53)     NULL,
    [Cloquet]                FLOAT (53)     NULL,
    [Cohasset]               FLOAT (53)     NULL,
    [Cokato]                 FLOAT (53)     NULL,
    [Cold Spring]            FLOAT (53)     NULL,
    [Coleraine]              FLOAT (53)     NULL,
    [Cologne]                FLOAT (53)     NULL,
    [Columbia Heights]       FLOAT (53)     NULL,
    [Coon Rapids]            FLOAT (53)     NULL,
    [Corcoran]               FLOAT (53)     NULL,
    [Cottage Grove]          FLOAT (53)     NULL,
    [Cottonwood]             FLOAT (53)     NULL,
    [Crookston]              FLOAT (53)     NULL,
    [Crosby]                 FLOAT (53)     NULL,
    [Cross Lake]             FLOAT (53)     NULL,
    [Crystal]                FLOAT (53)     NULL,
    [Dassel]                 FLOAT (53)     NULL,
    [Dawson]                 FLOAT (53)     NULL,
    [Dayton]                 FLOAT (53)     NULL,
    [Deephaven]              FLOAT (53)     NULL,
    [Delano]                 FLOAT (53)     NULL,
    [Dellwood]               FLOAT (53)     NULL,
    [Detroit Lakes]          FLOAT (53)     NULL,
    [Dilworth]               FLOAT (53)     NULL,
    [Dodge Center]           FLOAT (53)     NULL,
    [Duluth]                 FLOAT (53)     NULL,
    [Eagan]                  FLOAT (53)     NULL,
    [Eagle Lake]             FLOAT (53)     NULL,
    [East Bethel]            FLOAT (53)     NULL,
    [East Grand Forks]       FLOAT (53)     NULL,
    [East Gull Lake]         FLOAT (53)     NULL,
    [Eden Prairie]           FLOAT (53)     NULL,
    [Edina]                  FLOAT (53)     NULL,
    [Elbow Lake]             FLOAT (53)     NULL,
    [Elk River]              FLOAT (53)     NULL,
    [Ely]                    FLOAT (53)     NULL,
    [Eveleth]                FLOAT (53)     NULL,
    [Excelsior]              FLOAT (53)     NULL,
    [Eyota]                  FLOAT (53)     NULL,
    [Fairfax]                FLOAT (53)     NULL,
    [Fairmont]               FLOAT (53)     NULL,
    [Falcon Heights]         FLOAT (53)     NULL,
    [Faribault]              FLOAT (53)     NULL,
    [Farmington]             FLOAT (53)     NULL,
    [Fergus Falls]           FLOAT (53)     NULL,
    [Foley]                  FLOAT (53)     NULL,
    [Forest Lake]            FLOAT (53)     NULL,
    [Fosston]                FLOAT (53)     NULL,
    [Frazee]                 FLOAT (53)     NULL,
    [Fridley]                FLOAT (53)     NULL,
    [Fulda]                  FLOAT (53)     NULL,
    [Gaylord]                FLOAT (53)     NULL,
    [Gilbert]                FLOAT (53)     NULL,
    [Glencoe]                FLOAT (53)     NULL,
    [Glenwood]               FLOAT (53)     NULL,
    [Glyndon]                FLOAT (53)     NULL,
    [Golden Valley]          FLOAT (53)     NULL,
    [Goodview]               FLOAT (53)     NULL,
    [Grand Marais]           FLOAT (53)     NULL,
    [Grand Rapids]           FLOAT (53)     NULL,
    [Granite Falls]          FLOAT (53)     NULL,
    [Grant]                  FLOAT (53)     NULL,
    [Greenfield]             FLOAT (53)     NULL,
    [Hallock]                FLOAT (53)     NULL,
    [Ham Lake]               FLOAT (53)     NULL,
    [Hanover]                FLOAT (53)     NULL,
    [Harmony]                FLOAT (53)     NULL,
    [Harris]                 FLOAT (53)     NULL,
    [Hastings]               FLOAT (53)     NULL,
    [Hawley]                 FLOAT (53)     NULL,
    [Hayfield]               FLOAT (53)     NULL,
    [Hector]                 FLOAT (53)     NULL,
    [Hermantown]             FLOAT (53)     NULL,
    [Hibbing]                FLOAT (53)     NULL,
    [Hinckley]               FLOAT (53)     NULL,
    [Hopkins]                FLOAT (53)     NULL,
    [Houston]                FLOAT (53)     NULL,
    [Howard Lake]            FLOAT (53)     NULL,
    [Hoyt Lakes]             FLOAT (53)     NULL,
    [Hugo]                   FLOAT (53)     NULL,
    [Hutchinson]             FLOAT (53)     NULL,
    [Independence]           FLOAT (53)     NULL,
    [International Falls]    FLOAT (53)     NULL,
    [Inver Grove Heights]    FLOAT (53)     NULL,
    [Isanti]                 FLOAT (53)     NULL,
    [Jackson]                FLOAT (53)     NULL,
    [Janesville]             FLOAT (53)     NULL,
    [Jordan]                 FLOAT (53)     NULL,
    [Kasson]                 FLOAT (53)     NULL,
    [Keewatin]               FLOAT (53)     NULL,
    [Kenyon]                 FLOAT (53)     NULL,
    [La Crescent]            FLOAT (53)     NULL,
    [Lake City]              FLOAT (53)     NULL,
    [Lake Crystal]           FLOAT (53)     NULL,
    [Lake Elmo]              FLOAT (53)     NULL,
    [Lake Fremont]           FLOAT (53)     NULL,
    [Lake Saint Croix Beach] FLOAT (53)     NULL,
    [Lake Shore]             FLOAT (53)     NULL,
    [Lakefield]              FLOAT (53)     NULL,
    [Lakeland]               FLOAT (53)     NULL,
    [Lakeville]              FLOAT (53)     NULL,
    [Lauderdale]             FLOAT (53)     NULL,
    [Le Center]              FLOAT (53)     NULL,
    [Le Sueur]               FLOAT (53)     NULL,
    [Lester Prairie]         FLOAT (53)     NULL,
    [Lewiston]               FLOAT (53)     NULL,
    [Lexington]              FLOAT (53)     NULL,
    [Lindstrom]              FLOAT (53)     NULL,
    [Lino Lakes]             FLOAT (53)     NULL,
    [Litchfield]             FLOAT (53)     NULL,
    [Little Canada]          FLOAT (53)     NULL,
    [Little Falls]           FLOAT (53)     NULL,
    [Little Rock]            FLOAT (53)     NULL,
    [Long Lake]              FLOAT (53)     NULL,
    [Long Prairie]           FLOAT (53)     NULL,
    [Lonsdale]               FLOAT (53)     NULL,
    [Luverne]                FLOAT (53)     NULL,
    [Madelia]                FLOAT (53)     NULL,
    [Madison]                FLOAT (53)     NULL,
    [Mahnomen]               FLOAT (53)     NULL,
    [Mahtomedi]              FLOAT (53)     NULL,
    [Mankato]                FLOAT (53)     NULL,
    [Mantorville]            FLOAT (53)     NULL,
    [Maple Grove]            FLOAT (53)     NULL,
    [Maple Lake]             FLOAT (53)     NULL,
    [Maple Plain]            FLOAT (53)     NULL,
    [Mapleton]               FLOAT (53)     NULL,
    [Maplewood]              FLOAT (53)     NULL,
    [Marshall]               FLOAT (53)     NULL,
    [Medford]                FLOAT (53)     NULL,
    [Medina]                 FLOAT (53)     NULL,
    [Melrose]                FLOAT (53)     NULL,
    [Menahga]                FLOAT (53)     NULL,
    [Mendota Heights]        FLOAT (53)     NULL,
    [Milaca]                 FLOAT (53)     NULL,
    [Minneapolis]            FLOAT (53)     NULL,
    [Minneota]               FLOAT (53)     NULL,
    [Minnetonka]             FLOAT (53)     NULL,
    [Minnetonka Mills]       FLOAT (53)     NULL,
    [Minnetrista]            FLOAT (53)     NULL,
    [Montevideo]             FLOAT (53)     NULL,
    [Montgomery]             FLOAT (53)     NULL,
    [Monticello]             FLOAT (53)     NULL,
    [Montrose]               FLOAT (53)     NULL,
    [Moorhead]               FLOAT (53)     NULL,
    [Moose Lake]             FLOAT (53)     NULL,
    [Mora]                   FLOAT (53)     NULL,
    [Morris]                 FLOAT (53)     NULL,
    [Morristown]             FLOAT (53)     NULL,
    [Mound]                  FLOAT (53)     NULL,
    [Mounds View]            FLOAT (53)     NULL,
    [Mountain Iron]          FLOAT (53)     NULL,
    [Mountain Lake]          FLOAT (53)     NULL,
    [New Brighton]           FLOAT (53)     NULL,
    [New Hope]               FLOAT (53)     NULL,
    [New London]             FLOAT (53)     NULL,
    [New Prague]             FLOAT (53)     NULL,
    [New Richland]           FLOAT (53)     NULL,
    [New Ulm]                FLOAT (53)     NULL,
    [New York Mills]         FLOAT (53)     NULL,
    [Newport]                FLOAT (53)     NULL,
    [Nicollet]               FLOAT (53)     NULL,
    [Nisswa]                 FLOAT (53)     NULL,
    [North Branch]           FLOAT (53)     NULL,
    [North Mankato]          FLOAT (53)     NULL,
    [North Oaks]             FLOAT (53)     NULL,
    [North Saint Paul]       FLOAT (53)     NULL,
    [Northfield]             FLOAT (53)     NULL,
    [Norwood Young America]  FLOAT (53)     NULL,
    [Oak Grove]              FLOAT (53)     NULL,
    [Oak Park Heights]       FLOAT (53)     NULL,
    [Oakdale]                FLOAT (53)     NULL,
    [Oakport]                FLOAT (53)     NULL,
    [Olivia]                 FLOAT (53)     NULL,
    [Orono]                  FLOAT (53)     NULL,
    [Ortonville]             FLOAT (53)     NULL,
    [Osakis]                 FLOAT (53)     NULL,
    [Osseo]                  FLOAT (53)     NULL,
    [Otsego]                 FLOAT (53)     NULL,
    [Owatonna]               FLOAT (53)     NULL,
    [Park Rapids]            FLOAT (53)     NULL,
    [Parkers Prairie]        FLOAT (53)     NULL,
    [Paynesville]            FLOAT (53)     NULL,
    [Pelican Rapids]         FLOAT (53)     NULL,
    [Perham]                 FLOAT (53)     NULL,
    [Pierz]                  FLOAT (53)     NULL,
    [Pine City]              FLOAT (53)     NULL,
    [Pine Island]            FLOAT (53)     NULL,
    [Pipestone]              FLOAT (53)     NULL,
    [Plainview]              FLOAT (53)     NULL,
    [Plymouth]               FLOAT (53)     NULL,
    [Preston]                FLOAT (53)     NULL,
    [Princeton]              FLOAT (53)     NULL,
    [Prior Lake]             FLOAT (53)     NULL
);

