CREATE TABLE [dbo].[tblCityDistances2] (
    [F1]                NVARCHAR (255) NULL,
    [Proctor]           FLOAT (53)     NULL,
    [Ramsey]            FLOAT (53)     NULL,
    [Red Lake]          FLOAT (53)     NULL,
    [Red Lake Falls]    FLOAT (53)     NULL,
    [Red Wing]          FLOAT (53)     NULL,
    [Redby]             FLOAT (53)     NULL,
    [Redwood Falls]     FLOAT (53)     NULL,
    [Renville]          FLOAT (53)     NULL,
    [Rice]              FLOAT (53)     NULL,
    [Richfield]         FLOAT (53)     NULL,
    [Richmond]          FLOAT (53)     NULL,
    [Robbinsdale]       FLOAT (53)     NULL,
    [Rochester]         FLOAT (53)     NULL,
    [Rock Creek]        FLOAT (53)     NULL,
    [Rockford]          FLOAT (53)     NULL,
    [Rockville]         FLOAT (53)     NULL,
    [Rogers]            FLOAT (53)     NULL,
    [Roseau]            FLOAT (53)     NULL,
    [Rosemount]         FLOAT (53)     NULL,
    [Roseville]         FLOAT (53)     NULL,
    [Rush City]         FLOAT (53)     NULL,
    [Rushford]          FLOAT (53)     NULL,
    [Saint Anthony]     FLOAT (53)     NULL,
    [Saint Augusta]     FLOAT (53)     NULL,
    [Saint Bonifacius]  FLOAT (53)     NULL,
    [Saint Charles]     FLOAT (53)     NULL,
    [Saint Cloud]       FLOAT (53)     NULL,
    [Saint Francis]     FLOAT (53)     NULL,
    [Saint James]       FLOAT (53)     NULL,
    [Saint Joseph]      FLOAT (53)     NULL,
    [Saint Louis Park]  FLOAT (53)     NULL,
    [Saint Michael]     FLOAT (53)     NULL,
    [Saint Paul]        FLOAT (53)     NULL,
    [Saint Paul Park]   FLOAT (53)     NULL,
    [Saint Peter]       FLOAT (53)     NULL,
    [Sandstone]         FLOAT (53)     NULL,
    [Sartell]           FLOAT (53)     NULL,
    [Sauk Centre]       FLOAT (53)     NULL,
    [Sauk Rapids]       FLOAT (53)     NULL,
    [Savage]            FLOAT (53)     NULL,
    [Shakopee]          FLOAT (53)     NULL,
    [Sherburn]          FLOAT (53)     NULL,
    [Shoreview]         FLOAT (53)     NULL,
    [Shorewood]         FLOAT (53)     NULL,
    [Silver Bay]        FLOAT (53)     NULL,
    [Slayton]           FLOAT (53)     NULL,
    [Sleepy Eye]        FLOAT (53)     NULL,
    [South Saint Paul]  FLOAT (53)     NULL,
    [Spicer]            FLOAT (53)     NULL,
    [Spring Grove]      FLOAT (53)     NULL,
    [Spring Lake Park]  FLOAT (53)     NULL,
    [Spring Park]       FLOAT (53)     NULL,
    [Spring Valley]     FLOAT (53)     NULL,
    [Springfield]       FLOAT (53)     NULL,
    [Stacy]             FLOAT (53)     NULL,
    [Staples]           FLOAT (53)     NULL,
    [Starbuck]          FLOAT (53)     NULL,
    [Stewartville]      FLOAT (53)     NULL,
    [Stillwater]        FLOAT (53)     NULL,
    [Taylors Falls]     FLOAT (53)     NULL,
    [Thief River Falls] FLOAT (53)     NULL,
    [Tonka Bay]         FLOAT (53)     NULL,
    [Tracy]             FLOAT (53)     NULL,
    [Truman]            FLOAT (53)     NULL,
    [Two Harbors]       FLOAT (53)     NULL,
    [Tyler]             FLOAT (53)     NULL,
    [Vadnais Heights]   FLOAT (53)     NULL,
    [Victoria]          FLOAT (53)     NULL,
    [Virginia]          FLOAT (53)     NULL,
    [Wabasha]           FLOAT (53)     NULL,
    [Waconia]           FLOAT (53)     NULL,
    [Wadena]            FLOAT (53)     NULL,
    [Waite Park]        FLOAT (53)     NULL,
    [Walker]            FLOAT (53)     NULL,
    [Wanamingo]         FLOAT (53)     NULL,
    [Warren]            FLOAT (53)     NULL,
    [Warroad]           FLOAT (53)     NULL,
    [Waseca]            FLOAT (53)     NULL,
    [Watertown]         FLOAT (53)     NULL,
    [Waterville]        FLOAT (53)     NULL,
    [Wayzata]           FLOAT (53)     NULL,
    [Wells]             FLOAT (53)     NULL,
    [West Coon Rapids]  FLOAT (53)     NULL,
    [West Saint Paul]   FLOAT (53)     NULL,
    [Wheaton]           FLOAT (53)     NULL,
    [White Bear Lake]   FLOAT (53)     NULL,
    [Willmar]           FLOAT (53)     NULL,
    [Windom]            FLOAT (53)     NULL,
    [Winnebago]         FLOAT (53)     NULL,
    [Winona]            FLOAT (53)     NULL,
    [Winsted]           FLOAT (53)     NULL,
    [Winthrop]          FLOAT (53)     NULL,
    [Woodbury]          FLOAT (53)     NULL,
    [Worthington]       FLOAT (53)     NULL,
    [Wyoming]           FLOAT (53)     NULL,
    [Zumbrota]          FLOAT (53)     NULL
);

