CREATE TABLE [dbo].[tblEzClaimAddressRptOld] (
    [tblEZClaim_ID]         INT           IDENTITY (1, 1) NOT NULL,
    [TripID]                INT           NULL,
    [Insurance]             VARCHAR (50)  NULL,
    [ClientID]              INT           NULL,
    [Client]                VARCHAR (255) NULL,
    [RideDate]              DATETIME      NULL,
    [TripType]              VARCHAR (255) NULL,
    [LegCountNotCanceled]   INT           NULL,
    [LegNoShowCount]        INT           NULL,
    [Diagnosis1]            VARCHAR (20)  NULL,
    [RenderingPHYFID]       INT           NULL,
    [FacilityAddressID]     INT           NULL,
    [FacilityName]          VARCHAR (255) NULL,
    [AuthCode]              VARCHAR (255) NULL,
    [RepID]                 VARCHAR (255) NULL,
    [MemberID]              VARCHAR (30)  NULL,
    [ReimburseRate]         MONEY         NULL,
    [UnloadedReimburseRate] MONEY         NULL,
    [SumOfLoadedMiles]      INT           NULL,
    [SumOfUnloadedMiles]    INT           NULL,
    [DeadHeadAuth]          INT           NULL,
    [PaidUnloadedMiles]     INT           NULL,
    [TotalTripMiles]        INT           NULL,
    [PaidMiles]             INT           NULL,
    [UnpaidMiles]           INT           NULL,
    [MealsMisc]             MONEY         NULL,
    [BillingAmount]         MONEY         NULL,
    [Insuranceid]           INT           NULL,
    [SelectRecord]          BIT           NOT NULL,
    [EzClaimPhysicianID]    INT           NULL,
    [PatientID]             INT           NULL,
    [SeqNo]                 INT           NULL,
    [EzLinkID]              INT           NULL,
    [SplitLoadedMiles]      INT           NULL,
    [SplitUnLoadedMiles]    INT           NULL,
    [Warning]               VARCHAR (255) NULL,
    [Fee]                   MONEY         NULL,
    [UserName]              VARCHAR (50)  NULL,
    [CountFacility]         INT           NULL,
    CONSTRAINT [PK_tblEzClaimAROLD] PRIMARY KEY CLUSTERED ([tblEZClaim_ID] ASC)
);

