CREATE TABLE [dbo].[tblInsuranceBillingRPT] (
    [InsuranceBillID]         INT          IDENTITY (1, 1) NOT NULL,
    [County]                  VARCHAR (30) NULL,
    [RideDate]                DATETIME     NULL,
    [Client]                  VARCHAR (50) NULL,
    [Authorization Code]      VARCHAR (25) NULL,
    [MemberID]                VARCHAR (25) NULL,
    [LoadedMiles]             INT          NULL,
    [UnloadedMiles]           INT          NULL,
    [Total Miles]             INT          NULL,
    [Meals]                   MONEY        NULL,
    [Misc]                    MONEY        NULL,
    [UnloadedMilesTrue]       INT          NULL,
    [AllowMealsTrue]          INT          NULL,
    [Fee]                     MONEY        NULL,
    [Total Mileage Expense]   MONEY        NULL,
    [Total Billed]            MONEY        NULL,
    [MA Ride]                 CHAR (1)     NULL,
    [Waiver]                  CHAR (1)     NULL,
    [Child/Fam No Waiver]     CHAR (1)     NULL,
    [Adult Service No Waiver] CHAR (1)     NULL,
    [Public Health No Waiver] CHAR (1)     NULL,
    [AC Client Medical]       CHAR (1)     NULL,
    [On Going]                CHAR (1)     NULL,
    [New For Rides]           CHAR (1)     NULL,
    [Round Trip]              CHAR (1)     NULL,
    [One Way]                 CHAR (1)     NULL,
    [UserName]                VARCHAR (50) NULL,
    [RepID]                   VARCHAR (25) NULL,
    [ClDOB]                   DATETIME     NULL,
    [PendPaperwork]           CHAR (10)    NULL,
    [Worker]                  VARCHAR (50) NULL,
    [EzclaimClaimID]          INT          NULL,
    CONSTRAINT [PK_tblInsuranceBillingRPT] PRIMARY KEY CLUSTERED ([InsuranceBillID] ASC)
);

