CREATE TABLE [dbo].[tblMergeDriver] (
    [MergeDriverID]         INT            IDENTITY (1, 1) NOT NULL,
    [DriverID]              INT            NULL,
    [Active]                BIT            NULL,
    [EntryDate]             DATETIME       NULL,
    [DrFirstName]           NVARCHAR (255) NULL,
    [DrLastName]            NVARCHAR (255) NULL,
    [DrDOB]                 DATETIME       NULL,
    [DrStreetAddress]       NVARCHAR (255) NULL,
    [DrMailAddress]         NVARCHAR (255) NULL,
    [DrCity]                NVARCHAR (255) NULL,
    [DrState]               NVARCHAR (2)   NULL,
    [DrZip]                 INT            NULL,
    [DrPhone1]              NVARCHAR (255) NULL,
    [DrPhoneAlt]            NVARCHAR (255) NULL,
    [DrInsuranceProvider]   NVARCHAR (255) NULL,
    [DrInsurancePolicyNO]   NVARCHAR (255) NULL,
    [DrInsPolicyExp]        DATETIME       NULL,
    [DrLicenseNo]           NVARCHAR (255) NULL,
    [FMPDriverID]           INT            NULL,
    [DrNotes]               NTEXT          NULL,
    [LNFN]                  NVARCHAR (255) NULL,
    [upsize_ts]             ROWVERSION     NULL,
    [Email]                 NVARCHAR (50)  NULL,
    [DrMI]                  NVARCHAR (50)  NULL,
    [RRMed]                 NCHAR (10)     NULL,
    [DrLicenseExpires]      DATE           NULL,
    [MDRCheck]              DATE           NULL,
    [BackgroundCheck]       DATE           NULL,
    [DirectDeposit]         INT            NULL,
    [Vehicle]               NVARCHAR (50)  NULL,
    [Plate]                 NCHAR (10)     NULL,
    [VIN]                   NVARCHAR (50)  NULL,
    [HandicappedNumber]     NVARCHAR (50)  NULL,
    [HandicapExp]           DATE           NULL,
    [HandicapIssued]        DATE           NULL,
    [UserCreate]            CHAR (30)      NULL,
    [UserUpdated]           CHAR (30)      NULL,
    [DateUpdated]           DATETIME       NULL,
    [BuddyList]             BIT            NULL,
    [CountyID]              INT            NULL,
    [DuluthOnly]            BIT            NULL,
    [BuddyAdvocate]         NVARCHAR (50)  NULL,
    [LicenseExpires]        DATETIME       NULL,
    [DrMDRCheck]            DATETIME       NULL,
    [BGCheck]               DATETIME       NULL,
    [EmergencyContactName]  NCHAR (50)     NULL,
    [EmergencyContactPhone] NCHAR (30)     NULL,
    [TrainingDate]          DATETIME       NULL,
    [Deleted]               BIT            NULL
);

