CREATE TABLE [dbo].[tblMergeArchiveRide] (
    [MergeRideID]                  INT            IDENTITY (1, 1) NOT NULL,
    [RideID]                       INT            NULL,
    [EntryDate]                    DATETIME       NULL,
    [ClientID]                     INT            NULL,
    [ClFN]                         NVARCHAR (255) NULL,
    [ClLN]                         NVARCHAR (255) NULL,
    [ClPhone]                      NVARCHAR (255) NULL,
    [tblClient_ClientType]         INT            NULL,
    [tblClient_MemberID]           NVARCHAR (255) NULL,
    [ClNotes]                      NTEXT          NULL,
    [ltblClientType_ClientType]    NVARCHAR (255) NULL,
    [tblClientInsurance_MemberID]  NVARCHAR (255) NULL,
    [ClientInsuranceNotes]         NTEXT          NULL,
    [MaxAllowedByInsurancePerTrip] MONEY          NULL,
    [RPickupZip]                   INT            NULL,
    [tblRide_County]               INT            NULL,
    [ltblCounty_County]            NVARCHAR (255) NULL,
    [ltblCounty_MIPCountyCode]     NVARCHAR (255) NULL,
    [TripPurposeID]                INT            NULL,
    [TripPurpose]                  NVARCHAR (255) NULL,
    [TripTypeID]                   INT            NULL,
    [TripType]                     NVARCHAR (255) NULL,
    [RDropoffCounty]               INT            NULL,
    [ltblCounty_2_County]          NVARCHAR (255) NULL,
    [ltblCounty_2_MIPCountyCode]   NVARCHAR (255) NULL,
    [Insurance]                    NVARCHAR (255) NULL,
    [RequireIDandAuth]             BIT            NULL,
    [ArchiveUser]                  VARCHAR (25)   NULL,
    [ArchiveDateTime]              DATETIME       NULL
);

