CREATE TABLE [dbo].[tblMergeRideDeleted] (
    [MergeRideID]          INT            IDENTITY (1, 1) NOT NULL,
    [RideID]               INT            NULL,
    [EntryDate]            DATETIME       NULL,
    [ClientID]             INT            NULL,
    [RPickUpAddress]       NVARCHAR (255) NULL,
    [RPickupCity]          NVARCHAR (255) NULL,
    [RPickupZip]           VARCHAR (15)   NULL,
    [County]               INT            NULL,
    [TripPurposeID]        INT            NULL,
    [TripTypeID]           INT            NULL,
    [RideDate]             DATETIME       NULL,
    [RStartTime]           DATETIME       NULL,
    [REndTime]             DATETIME       NULL,
    [RTripTime]            INT            NULL,
    [RDropoffAddress]      NVARCHAR (255) NULL,
    [RDropoffCity]         NVARCHAR (255) NULL,
    [RDropoffZip]          VARCHAR (15)   NULL,
    [RDropoffCounty]       INT            NULL,
    [LoadedMiles]          INT            NULL,
    [UnloadedMiles]        INT            NULL,
    [TotalMiles]           INT            NULL,
    [MNDOTAllow]           BIT            NULL,
    [ElderlyWaiver]        BIT            NULL,
    [Overnight]            BIT            NULL,
    [AuthCode]             NVARCHAR (255) NULL,
    [RepID]                NVARCHAR (255) NULL,
    [PickupFee]            MONEY          NULL,
    [NoShowFee]            MONEY          NULL,
    [FMPRIdeID]            INT            NULL,
    [TripID]               INT            NULL,
    [FMPTripID]            INT            NULL,
    [InsuranceID]          INT            NULL,
    [Rate]                 MONEY          NULL,
    [RideNotes]            NTEXT          NULL,
    [SchedulePickupTime]   DATETIME       NULL,
    [ScheduleApptTime]     DATETIME       NULL,
    [Canceled]             BIT            NULL,
    [ReimburseRate]        MONEY          NULL,
    [ReimburseRateID]      INT            NULL,
    [Assigned]             BIT            NULL,
    [NoShow]               BIT            NULL,
    [OldAccessDbRideID]    INT            NULL,
    [RequireIDandAuth]     BIT            NULL,
    [upsize_ts]            ROWVERSION     NULL,
    [DriverID]             INT            NULL,
    [SelectCheck]          BIT            NULL,
    [UserCreated]          CHAR (30)      NULL,
    [UserUpdated]          CHAR (30)      NULL,
    [DateUpdated]          DATETIME       NULL,
    [DispatchAccessRideID] INT            NULL,
    [RequireAuthCode]      BIT            NULL,
    [ClientInsuranceID]    INT            NULL,
    [MemberID]             NCHAR (30)     NULL,
    [Lock]                 BIT            NULL,
    [FacilityName]         NVARCHAR (255) NULL,
    [SeqNo]                INT            NULL,
    [PUAddressID]          INT            NULL,
    [DOAddressID]          INT            NULL,
    [RPickupZip4]          CHAR (4)       NULL,
    [RDropOffZip4]         CHAR (4)       NULL,
    [FaciltyZip4]          BIT            NULL,
    [SeniorFitness]        BIT            NULL,
    [rPickupState]         NCHAR (2)      NULL,
    [rDropOffState]        NCHAR (2)      NULL,
    [rCancelReason]        INT            NULL,
    [InEzClaim]            BIT            NULL,
    [MnITSWaver]           BIT            NULL,
    [ChildFamNoWaver]      BIT            NULL,
    [AdultServiceWaver]    BIT            NULL,
    [PublicHealthNoWaver]  BIT            NULL,
    [OnGoing]              BIT            NULL,
    [NewForRides]          BIT            NULL,
    [RoundTrip]            BIT            NULL,
    [OneWay]               BIT            NULL,
    [Waver]                BIT            NULL,
    [MARide]               BIT            NULL,
    [AdultServiceNoWaiver] BIT            NULL,
    [ACClientMedical]      BIT            NULL,
    [PUAddressTypeID]      INT            NULL,
    [DOAddressTypeID]      INT            NULL,
    [EzLinkID]             INT            NULL,
    [ezclaimphysicianid]   INT            NULL
);

